errbit:
  image: integralagile/errbit:latest
  ports:
    - "80:8080"
  links:
    - mongo
  environment:
    - PORT=8080
    - RACK_ENV=production
    - MONGO_URL=mongodb://mongo:27017/errbit
mongo:
  image: mongo:3.4
  ports:
    - "27017"
