#!/bin/zsh
#update the fork
#BE SURE TO not be in a docker-machine session
#NOTE: may need to migrate mongodb by incrementally loading different versions:
# db.adminCommand( { getParameter: 1, featureCompatibilityVersion: 1 } )
# db.adminCommand( { setFeatureCompatibilityVersion: "<next version>" } )
git fetch upstream
git checkout master
git rebase upstream/master
git push -f origin master
git checkout integral-agile-customization
if git merge master; then
  bundle install
  gac "updated Gemfile"
  git push
  docker build -t errbit .
  docker tag errbit:latest integralagile/errbit:latest
  docker login -u integralagile --password-stdin
  docker push integralagile/errbit:latest
  eval $(docker-machine env integralagile-errbit)
  docker login -u integralagile --password-stdin
  docker-compose pull errbit
  docker-compose down
  docker-compose up -d
fi
