#!/bin/zsh
git merge origin master
docker build -t errbit .
docker login
docker push integralagile/errbit:latest
eval $(docker-machine env integralagile-errbit)
docker-compose down
docker-compose pull errbit
docker-compose up -d
